baseURL: "https://blog.zeroday0619.dev"
title: "zeroday0619's Programming Life"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: ""

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
      - HTML
      - RSS
      - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "zeroday0619's Programming Life"
    description: "í”„ë¡œì íŠ¸ & ìŠ¤í„°ë”” í•˜ë©´ì„œ ì•Œê²Œ ëœê±¸ ì •ë¦¬í•˜ëŠ” ê³µê°„"
    keywords: ["ì»´í“¨í„° ê³µí•™", "ë¦¬ëˆ…ìŠ¤", "í”„ë¡œê·¸ë˜ë°"]
    author: "zeroday0619"
    images: ["https://media.discordapp.net/attachments/829169388871090196/869135001541828628/1500x500.png"]
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: false
        # disableFingerprinting: false
        favicon: "https://media.discordapp.net/attachments/829169388871090196/869156130964791347/unknown.png"
        favicon16x16: "https://media.discordapp.net/attachments/829169388871090196/869156130964791347/unknown.png?width=16&height=16"
        favicon32x32: "https://media.discordapp.net/attachments/829169388871090196/869156130964791347/unknown.png?width=32&height=32"
        apple_touch_icon: "https://media.discordapp.net/attachments/829169388871090196/869156130964791347/unknown.png?width=144&height=144"
        safari_pinned_tab: "https://media.discordapp.net/attachments/829169388871090196/869156130964791347/unknown.png"

    label:
        text: "ğŸ "
  
    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            *Welcome to my blog in "zeroday 0619 Programming Life"*\

             Written by [@zeroday0619](about/)

    socialIcons:
        - name: twitch
          url: "https://twitch.tv/zeroday0619"
        - name: twitter
          url: "https://twitter.com/dev_zeroday0619"
        - name: github
          url: "https://github.com/zeroday0619"
        - name: buymeacoffee
          url: "https://toss.me/zeroday"


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/zeroday0619/blog/edit/main/content"
        Text: "ìˆ˜ì •í•˜ê¸°" # edit text
        appendFilePath: true # to append file path to Edit link
    # for sarch
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]


menu:
    main:
        - name: ê²€ìƒ‰
          url: /search
        - name: ì¹´í…Œê³ ë¦¬
          url: /categories
        - name: íƒœê·¸
          url: /tags
        - name: ì•„ì¹´ì´ë¸Œ
          url: /archives