baseURL: "https://blog.zeroday0619.dev"
title: "zeroday0619's Programming Life"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-4Y10MDKFEZ"

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
      - HTML
      - RSS
      - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "zeroday0619's Programming Life"
    description: "í”„ë¡œì íŠ¸ & ìŠ¤í„°ë”” í•˜ë©´ì„œ ì•Œê²Œ ëœê±¸ ì •ë¦¬í•˜ëŠ” ê³µê°„"
    keywords: ["ì»´í“¨í„° ê³µí•™", "ë¦¬ëˆ…ìŠ¤", "í”„ë¡œê·¸ë˜ë°"]
    author: "zeroday0619"
    languageAltTitle: "Korean"  
    images: ["https://media.discordapp.net/attachments/829169388871090196/869135001541828628/1500x500.png"]
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    comments: true
    ShowPostNavLinks: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon.ico"
        favicon32x32: favicon.ico"
        apple_touch_icon: "favicon.png"
        safari_pinned_tab: "favicon.png"

    label:
        text: "ğŸ "
  
    # home-info mode
    homeInfoParams:
        Title: "zeroday0619's Programming Life"
        Content: >
            *Welcome to my blog in zeroday0619's Programming Life*\
            
            Written by [@zeroday0619](about/)

    socialIcons:
        - name: twitch
          url: "https://twitch.tv/zeroday0619"
        - name: twitter
          url: "https://twitter.com/dev_zeroday0619"
        - name: github
          url: "https://github.com/zeroday0619"
        - name: buymeacoffee
          url: "https://toss.me/zeroday"


    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/zeroday0619/blog/edit/main/content"
        Text: "ìˆ˜ì •í•˜ê¸°" # edit text
        appendFilePath: true # to append file path to Edit link
    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]


menu:
    main:
        - name: ê²€ìƒ‰
          url: /search
        - name: ì¹´í…Œê³ ë¦¬
          url: /categories
        - name: íƒœê·¸
          url: /tags
        - name: ì•„ì¹´ì´ë¸Œ
          url: /archives